application: soichi-mizutani
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: public/assets
  application_readable: true

- url: /.*
  script: _go_app
  secure: always

skip_files:
- ^(vendor/.*)
- ^(src/.*)
- ^(node_modules/.*)
