version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make deps
      - run: make build
      - deploy:
          command: |
            SRC="bin templates public"
            if [ "${CIRCLE_BRANCH}" == "quit-gae" ];
              rsync -av --delete -e "ssh -l ${SSH_USER_NAME} -p ${SSH_PORT}" ${SRC} ${HOST}:${TARGET}/
              ssh -p ${SSH_PORT} -l ${SSH_USER_NAME} ${HOST} "supervisorctl restart ${DOMAIN}"
            fi
