name = "Soichi Mizutani"
license = "MIT"
licenselink = "https://github.com/lowply/soichi-mizutani.com/blob/master/LICENSE"
description = "A Hugo theme for soichi-mizutani.com"
homepage = "https://soichi-mizutani.com/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "lowply"
  homepage = "https://lowply.github.io/"
